### ISSUE TITLE
send message for update

### ISSUE THREAD

**Issue by jasondreher** [BrianHepler/MMM-WeasleyClock#12]
I know this is an old module but I am tryin to get it to work with just a message update, what would my payload need to be here? I dont want to use owntracks as I have a location tracking system already in place.

http://192.168.0.50:8090/syslog?type=INFO&message=MMM-WeasleyClock-UPDATE&payload={person:Angie,inregions:Work}

Or how do I send a MQTT message to show someone changed location? The below seems to do something but does not move the arrow.
Topic:
owntracks/TheDrehers/Angie
Message:
{
  "_type": "location",
  "person": "Angie",
  "inregions": "Work"
}

**Comment by BrianHepler** [comment]
If you check out the file `developmentNotes.md` you should find some examples of the OwnTracks module payloads. With your example above, the `inregions` value is an array, so it should look like so:
```
{
"_type": "location",
"person": "Angie",
"inregions": ["Work"]
}
```
Give it a go and let me know if that resolves it.

**Comment by jasondreher** [comment]
Nice!!! That worked
