### ISSUE TITLE
Uncaught errors

### ISSUE THREAD

**Issue by jameshmcc** [BrianHepler/MMM-WeasleyClock#14]
I've been running this fantastic module for a couple of years, but today there is an issue with code that I've never touched - uncaught exceptions on a couple of the files. I initially thought it was the MQTT server but its not that. 

These are the errors

`[24.06.2024 16:28.56.737] [ERROR] Whoops! There was an uncaught exception...
[24.06.2024 16:28.56.740] [ERROR] TypeError: Cannot read properties of undefined (reading 'end')
    at Class.stop (/home/james/MagicMirror/modules/MMM-WeasleyClock/node_helper.js:26:15)
    at App.stop (/home/james/MagicMirror/js/app.js:254:16)
    at App.<anonymous> (/home/james/MagicMirror/js/electron.js:145:7)
    at App.emit (node:events:526:28)`
    
I can't see any issue with the code on these lines, and again there are no edits. Struggling to figure it out!

**Comment by BrianHepler** [comment]
Are you using my MQTT server? I am having trouble rebuilding it and it's been down for the past couple days. Regardless, the module should definitely handle the errors better.

As soon as I get my Mosquitto server running again, I'll look into this.

**Comment by BrianHepler** [comment]
Okay, the good news is that I think I have my Mosquitto server working properly. It should connect to your Owntracks and your mirror properly now. Please give it a go (you may have to restart your Magic Mirror process). Let me know if it is working again.

I'll do some work on error trapping so it doesn't crash the entire mirror the next time something goes weird.

**Comment by jameshmcc** [comment]
Hi Brian - yes, I was using your MQTT server - and everything is working again now. Thanks for fixing this - maybe I need to stop being lazy and sort my own MQTT server out!

Really love this module - I have it built into a old antique clock. Thanks for making this so accessible.
![IMG_7438](https://github.com/BrianHepler/MMM-WeasleyClock/assets/114289688/15e117b1-e9e2-4554-ad2a-acf9e62ea419)

**Comment by BrianHepler** [comment]
Wow. That's awesome. Great job!
