### ISSUE TITLE
Causing reboot of MagicMirror on Buster

### ISSUE THREAD

**Issue by Plainbroke** [BrianHepler/MMM-WeasleyClock#15]
My MagicMirror is coming up with an error about not being able to connect to weaslyclock@duckdns

**Comment by BrianHepler** [comment]
Yeah, I'm having problems with my Mosquitto server. I hope to have it fixed shortly. 
And once I do, I'm going to see about trapping those errors better so this doesn't happen again.

**Comment by BrianHepler** [comment]
Okay, I think I have the Mosquitto problems resolved. Please check to see if your mirror is connecting properly and displaying the Weasley Clock. You may have to restart the mirror process, but I think it should work now.

**Comment by Plainbroke** [comment]
@BrianHepler 
Good work my man.   Really appreciate the fix.. 
She will be happy when she see's it is working again.
