### ISSUE TITLE
OwnTracks

### ISSUE THREAD

**Issue by Sean-Amor** [BrianHepler/MMM-WeasleyClock#3]
I followed all the steps up until the certificate, I cannot select the certificate once I have downloaded it, I am using the IOS Version.
Also, under "status"
I get "Connecting"
Then idle NSPOSIXeErrorDomain 51 The operation couldn't be completed. Network is unreachable
{
  "kCFStreamErrorCodeKey" =51;
  "kCFStreamErrorDomainKey" =1;
}

Any suggestions?

**Comment by BrianHepler** [comment]
That may be a problem with my network. I'll look into it

(sorry about that - was replying from my phone)

**Comment by BrianHepler** [comment]
I found that the Pi that runs my mosquitto broker was down. I have reset it and verified that it is connected to my network. Please try again and let me know if you encounter more problems. My apologies for the inconvenience.

**Comment by Sean-Amor** [comment]
No problem at all! Thank you for your help! It appears to still be having
issues connecting, I may need an updated how to for the latest OwnTracks
app, its a bit differe, I have not figured out how to add the certificate
with my iPhone 7, its no longer jailbroken... I don’t know if that is
needed to add the certificate. I don’t know if any of these attachments
will be helpful. No rush at all I appreciate your help and time!



-- 

--------------------------------

Thanks!


*Sean*

*Senior Creative Artist*

*512.461.1934*

portfolio:

seanc.myportfolio.com

LinkedIn:

www.linkedin.com/in/sean-creatif-25b606128

paypal email/Link:

sean.david.amor@gmail.com

paypal.me/seanamor

venmo email/Link:

www.venmo.com/Sean-Amor

**Comment by BrianHepler** [comment]
I don't have an iPhone that I can use to test it. Have you checked out the iOS section of the OwnTracks website? This may help: https://owntracks.org/booklet/features/tlscert/#ios
