### ISSUE TITLE
Owntracks cant connect to server

### ISSUE THREAD

**Issue by bafplus** [BrianHepler/MMM-WeasleyClock#4]
Hy!

I just installed the module.
Chances are i did something wrong yet i double checked with the instructions in the Readme.

When Owntracks tries to connect it gives a "Error: MQTT Error: unable to connect to server"

**Comment by bafplus** [comment]
Did a telnet on the server and it seems dead, telnet response: "telnet: Unable to connect to remote host: No route to host"

**Comment by BrianHepler** [comment]
It's possible that my server is having problems. Give me an hour or so and I'll check on it.BrianOn Jun 3, 2021 7:27 AM, bafplus ***@***.***> wrote:
Hy!
I just installed the module.
Chances are i did something wrong yet i double checked with the instructions in the Readme.
When Owntracks tries to connect it gives a "Error: MQTT Error: unable to connect to server"

**Comment by bafplus** [comment]
Thanks in advance!
Im on the other side of the world so time for some shuteye ;-)

I tried al day building my own broker but hitting a wall with the certificates. If you have time, are you willing to help me setup my own server/broker? (mind im a noob so copy/paste stuff much apriciated ;-) )

**Comment by BrianHepler** [comment]
Okay, I have the server up & running again. Please try connecting again. We had a power outage a couple days ago and apparently it didn't recover gracefully.

I'll be happy to help get you set up. What are you using for the Mosquitto server? I have a 1st gen Pi doing the work for me, so it doesn't take much.

**Comment by BrianHepler** [comment]
Hrm. I can see what I think are your attempts to connect to my mosquitto server. I see recurring message that read:
`Socket error on client <unknown>, disconnecting.`
A quick search turned up that [same message in the Mosquitto project](https://github.com/eclipse/mosquitto/issues/1607). Research is ongoing.

**Comment by bafplus** [comment]
Good Morning :-)

That probably is me indeed, i have Ownstracks running on my Android phone and my Mirror. 
Both are set to use your broker.

Help in running my own would be great! I noticed you had planned to create a page for it in the repo.
I will document allong the way to create that page lateron.

Maybe its a good thing to connect on some more direct platform like Telegram, Discord or something?

**Comment by bafplus** [comment]
I tried using a public broker (https://www.hivemq.com/public-mqtt-broker/) and after disabling TLS in the helper i could succesfully connect to the broker with the module and my clients. 
So my best guess is something ssl related.

Found another bug with module set in table mode, see issue #6

**Comment by BrianHepler** [comment]
Oh cool. Yeah, the table view needs some help.
Discord might be useful, but with our different time zones that may be only practical on weekends. But let's keep that in mind as a possibility.

TLS is once again making things difficult. I haven't used the Owntracks app in a while. I'll install it again and see if I can get it working. I'll have updates for you soon.

**Comment by BrianHepler** [comment]
I did some work on this today. The new version of OwnTracks has apparently fixed a bug with not checking the hostname in the certificate. I'm updating my Mosquitto server and I'm going to rebuild the CA cert and see if that solves the problem.

After all that, I'm going to put together a tutorial on hosting the MQTT server yourself. You can do this on your mirror itself or any other always-on machine you have laying about.

**Comment by BrianHepler** [comment]
Fixed the issue with using self-signed certificates and the new version of OwnTracks. Please try out the TLS-Fix branch and the MQTT tutorial to host your own message broker on your mirror.
