### ISSUE TITLE
Clockstyle Table does not update its vallue

### ISSUE THREAD

**Issue by bafplus** [BrianHepler/MMM-WeasleyClock#6]
Uppun bugtracking Issue #4 i found an issue with the Clock in "table" layout.
When i run the module in clockmode it nicely changes its vallue when a new locationupdate is recieved.
However, when in tablemode the status does NOT change en everyone stays in "lost" status and the status is not update after a succesvol recieved and processed change in location.

**Comment by BrianHepler** [comment]
Yikes. Thanks for reporting this. I'll get on it.

**Comment by BrianHepler** [comment]
Table fix has been added to the latest release.
