### ISSUE TITLE
TLS Setup Failed

### ISSUE THREAD

**Issue by stevewilliams198** [BrianHepler/MMM-WeasleyClock#7]
Good afternoon, tried setting up the ownTracks as per the instructions.

Followed everything exactly (or so I thought). Matched the security file.
Within Parameters, I had to put in a value of Keepalive at 900, but turned on CleanSession.

On Status, I get the error, TLS Setup failed.

Is there anything I can do differently to ensure it works? Very new to this so not sure if its something silly gone wrong!
Thank you

**Comment by stevewilliams198** [comment]
![Screenshot_20210802-173902_Owntracks](https://user-images.githubusercontent.com/88247413/127895326-43110e05-00d9-412e-a383-fdfe93bbf8db.jpg)
![Screenshot_20210802-173912_Owntracks](https://user-images.githubusercontent.com/88247413/127895329-6cb4bbc4-1507-4778-94db-670fb848aac7.jpg)
![Screenshot_20210802-173906_Owntracks](https://user-images.githubusercontent.com/88247413/127895330-ba2a58e6-d623-4160-be1c-8c9f361e8c68.jpg)
![Screenshot_20210802-173857_Owntracks](https://user-images.githubusercontent.com/88247413/127895333-3e942784-ac0d-4ba5-b0d9-25877827b81f.jpg)
![Screenshot_20210802-173853_Owntracks](https://user-images.githubusercontent.com/88247413/127895334-a5e27f1b-e4db-44c1-8926-bb163d68424d.jpg)
![Screenshot_20210802-173848_Owntracks](https://user-images.githubusercontent.com/88247413/127895335-f8c13f85-2c63-477d-a82d-9f82b7a178b4.jpg)

Screenshots attached

**Comment by BrianHepler** [comment]
It turns out that Owntracks worked due to a flaw in the implementation of TLS. In the latest version of the app they fixed the flaw. The solution is (I think) to get a site certificate and distribute that instead of relying on the self-signed certificate. I'm working on it now.

**Comment by BrianHepler** [comment]
My apologies for the delay in fixing this. I have a PR ready to fix this issue. If you want, you can test out the TLS-Fix branch and let me know if it resolved your problems.
